// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpqwanaptxlfygiybner.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwcXdhbmFwdHhsZnlnaXlibmVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgxNDg3NDYsImV4cCI6MjA4MzcyNDc0Nn0.2IV9e9I5rvj_yfKoayd_fcPTDPrFCrZ7BAzuV4plVHM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);